import { MobParts } from 'src/app/models/mob-parts';

export const DBMOBPARTS: MobParts[] = [
  {
    id: 11112341,
    name: 'Screen 5.1 Apple',
    description: '5.1 Screen for Apple',
    inStock: 2000,
    price: 1200,
    country: 'Germany',
    prdImg: 'mobile4.jpg',
    clsVar: true,
    quantity: 0,
  },
  {
    id: 1002,
    name: 'Screen 5.2 apple',
    description: '5.2 Screen for Apple',
    inStock: 9,
    price: 1200,
    country: 'India',
    prdImg: 'mobile5.jpg',
    clsVar: true,
    quantity: 0,
  },
  {
    id: 1003,
    name: 'Screen 5.3 I-Phome 8',
    description: '5.3 Screen for I-Phone 8',
    inStock: 0,
    price: 1200,
    country: 'Australia',
    prdImg: 'mobile7.jpg',
    clsVar: true,
    quantity: 0,
  },
  {
    id: 1004,
    name: 'Screen 5.4 Samsung',
    description: '5.4 Screen for Samsung',
    inStock: 0,
    price: 100,
    country: 'India',
    prdImg: 'mobile6.jpg',
    clsVar: true,
    quantity: 0,
  },
];
